# Generated by Django 6.0.4 on 2026-04-30 14:39

import core.model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('VERIFICATION', 'Email/Phone Verification'), ('PASSWORD_RESET', 'Password Reset')], default='VERIFICATION', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expiry', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_modified'],
                'abstract': False,
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
    ]
