# Generated by Django 6.0.4 on 2026-05-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbank',
            old_name='lga',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='lga',
            new_name='area',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
