# Generated by Django 6.0.4 on 2026-05-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_lga_bloodbank_area_rename_lga_hospital_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
