# Generated by Django 6.0.4 on 2026-05-08 18:02

import core.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bloodbank_commission_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'verbose_name_plural': 'Global Configurations',
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
    ]
