# Generated by Django 6.0.4 on 2026-05-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_globalconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='address',
            field=models.TextField(blank=True, default='123 SwiftAid Tech Plaza, Lagos, Nigeria', null=True),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='contact_email',
            field=models.EmailField(blank=True, default='support@swiftaid.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='contact_phone',
            field=models.CharField(blank=True, default='+234 800 SWIFTAID', max_length=20, null=True),
        ),
    ]
