# Generated by Django 6.0.4 on 2026-05-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_globalconfig_address_globalconfig_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='allowed_free_payouts_counts',
            field=models.IntegerField(default=2, help_text='Number of free payouts per month for blood banks'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='payout_charge_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Flat fee charged after free payouts are exhausted', max_digits=10),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
