# Generated by Django 6.0.4 on 2026-05-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_bloodbank_wallet_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalconfig',
            old_name='allowed_free_payouts_counts',
            new_name='allowed_free_payouts',
        ),
    ]
