# Generated by Django 6.0.4 on 2026-05-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_allowed_free_payouts_counts_globalconfig_allowed_free_payouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
