# Generated by Django 6.0.4 on 2026-05-09 02:06

import core.model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_bloodbank_is_active_hospital_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified'), ('ACTIVATED', 'Activated'), ('DEACTIVATED', 'Deactivated')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_actions', to=settings.AUTH_USER_MODEL)),
                ('blood_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.bloodbank')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.hospital')),
            ],
            options={
                'verbose_name': 'Verification Log',
                'verbose_name_plural': 'Verification Logs',
                'ordering': ['-date_created'],
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
    ]
