# Generated by Django 6.0.4 on 2026-05-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_bloodbank_created_by_globalconfig_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
