# Generated by Django 6.0.4 on 2026-05-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_bloodbank_logistics_status_potentialdonor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bloodbank',
            unique_together={('name', 'country', 'state', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together={('name', 'country', 'state', 'city')},
        ),
    ]
