# Generated by Django 6.0.4 on 2026-05-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_email_alter_bloodbank_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='area',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='license_number',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='state',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='area',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
