# Generated by Django 6.0.4 on 2026-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_bloodbank_area_alter_bloodbank_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='area',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='license_number',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='state',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='area',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
    ]
