# Generated by Django 6.0.4 on 2026-05-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_bloodbank_area_alter_bloodbank_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
