# Generated by Django 6.0.4 on 2026-04-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='blood_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='transaction.bloodrequest'),
        ),
    ]
