# Generated by Django 6.0.4 on 2026-05-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='blood_bank_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount for blood bank', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Payment gateway fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform profit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount paid by customer', max_digits=10),
        ),
    ]
