# Generated by Django 6.0.4 on 2026-05-09 01:11

import core.model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_blood_bank_fee_payment_commission_percentage_and_more'),
        ('users', '0010_bloodbank_wallet_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=20)),
                ('recipient_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_internal_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('blood_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='users.bloodbank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_modified'],
                'abstract': False,
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount sent to recipient', max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee charged for this payout', max_digits=10)),
                ('total_debited', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount deducted from wallet', max_digits=10)),
                ('transaction_reference', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('is_internal_admin', models.BooleanField(default=False)),
                ('bank_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='payment.bankdetail')),
                ('blood_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='users.bloodbank')),
            ],
            options={
                'ordering': ['-last_modified'],
                'abstract': False,
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
    ]
