# Generated by Django 6.0.4 on 2026-04-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='source',
            field=models.CharField(choices=[('MARKETPLACE', 'Marketplace'), ('POS', 'Direct POS Sale'), ('WHATSAPP', 'WhatsApp Bot')], default='MARKETPLACE', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
