# Generated by Django 6.0.4 on 2026-05-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_bloodrequest_blood_price_bloodrequest_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='bloodbank',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='requester_org',
        ),
    ]
