# Generated by Django 6.0.4 on 2026-05-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_bloodrequest_bloodbank_and_more'),
        ('users', '0004_bloodbank_hospital_remove_userprofile_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='users.bloodbank'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='requester_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_bloods', to='users.hospital'),
        ),
    ]
