# Generated by Django 6.0.4 on 2026-05-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_bloodrequest_blood_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
