# Generated by Django 6.0.4 on 2026-05-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_bloodrequest_hospital_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
