# Generated by Django 6.0.4 on 2026-05-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_bloodrequest_commission_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='batch_id',
            field=models.CharField(blank=True, help_text='Groups multiple requests in one marketplace session', max_length=100, null=True),
        ),
    ]
