# Generated by Django 6.0.4 on 2026-05-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_bloodrequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='payment_method',
            field=models.CharField(choices=[('TRANSFER', 'Bank Transfer'), ('POS', 'POS Terminal'), ('CASH', 'Cash Payment')], default='TRANSFER', max_length=20),
        ),
    ]
