# Generated by Django 6.0.4 on 2026-05-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='organization',
        ),
    ]
