# Generated by Django 6.0.4 on 2026-05-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_organization'),
        ('users', '0004_bloodbank_hospital_remove_userprofile_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='blood_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='users.bloodbank'),
        ),
    ]
