# Generated by Django 6.0.4 on 2026-05-08 15:16

import core.model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_blood_bank'),
        ('users', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('donor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('volume_ml', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='users.bloodbank')),
            ],
            options={
                'ordering': ['-last_modified'],
                'abstract': False,
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
    ]
