# Generated by Django 6.0.4 on 2026-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
