# Generated by Django 6.0.4 on 2026-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_bloodtype_alter_inventory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='genotype',
            field=models.CharField(blank=True, help_text='e.g. AA, AS, AC, SS', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='hemoglobin_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hemoglobin level in g/dL', max_digits=5, null=True),
        ),
    ]
